# @format

version: '3.7'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: universalstore
      POSTGRES_PASSWORD: universalstore
      POSTGRES_DB: universalstore

  graphql:
    restart: always
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: ./server/Dockerfile
      args:
        ARG_POSTGRES_URL: 'postgresql://universalstore:universalstore@postgres:5432/universalstore?schema=universalstore'
    ports:
      - '4000:8080'
