require_relative '../../node_modules/react-native/scripts/react_native_pods'
require_relative '../../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../../node_modules/react-native-unimodules/cocoapods.rb'
platform :ios, '10.0'

target 'UniversalStore' do
  rn_maps_path = '../../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  permissions_path = '../../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"

  use_unimodules!(modules_paths: ['../../node_modules'])
  config = use_native_modules!
  use_react_native!(:path => config[:reactNativePath]) # https://github.com/facebook/react-native/issues/29371

  target 'UniversalStoreTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'UniversalStore-tvOS' do
  # Pods for UniversalStore-tvOS

  target 'UniversalStore-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
